[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.0",
    "requests>=2.32.3",
    "telegram>=0.0.1",
    "python-telegram-bot>=20.4",
]
